### ISSUE TITLE
Can we default a initial value? 

### ISSUE THREAD

**Issue by CharuGoyalS** [Zaydme/strapi-plugin-multi-select#34]
I want a default option for my multiselect field?  is it possible to choose a default option just like we have for Enumeration?

**Comment by Zaydme** [comment]
This feature is available on the latest version `strapi-plugin-multi-select@2.1.1`

Available since @2.1.0 https://github.com/Zaydme/strapi-plugin-multi-select/commit/58bff918524c33a19e7bd27d24cec8e445252a40

![multi-select-default-value.png](https://github.com/user-attachments/assets/72628cc4-cc8a-41e7-a456-32d86b792e8f)
